# Generated by Django 2.0.10 on 2019-01-11 13:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('parent_email', models.CharField(max_length=200, null=True, verbose_name="Parent's Email")),
                ('roll', models.CharField(max_length=10, null=True)),
                ('date', models.DateField(default=datetime.date(2019, 1, 11), null=True, verbose_name='Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('time', models.TimeField(default=datetime.time(13, 4, 50, 451487), null=True, verbose_name='Time')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='End Time')),
                ('venue', models.CharField(blank=True, max_length=512, verbose_name='Venue')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('perm', models.BooleanField(default=True, verbose_name='Permission Granted')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
