# Generated by Django 2.0.10 on 2019-01-11 13:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='time',
            field=models.TimeField(default=datetime.time(13, 30, 5, 123424), null=True, verbose_name='Time'),
        ),
    ]
