# Generated by Django 2.0.10 on 2019-01-11 13:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_auto_20190111_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='time',
            field=models.TimeField(default=datetime.time(13, 30, 10, 842497), null=True, verbose_name='Time'),
        ),
    ]
