# Generated by Django 2.0.10 on 2019-01-12 17:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0004_auto_20190111_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='date',
            field=models.DateField(default=datetime.date(2019, 1, 12), null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='request',
            name='perm',
            field=models.BooleanField(default=False, verbose_name='Permission Granted'),
        ),
        migrations.AlterField(
            model_name='request',
            name='time',
            field=models.TimeField(default=datetime.time(17, 43, 22, 898872), null=True, verbose_name='Time'),
        ),
    ]
