# Generated by Django 2.0.10 on 2019-01-13 06:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0005_auto_20190112_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='date',
            field=models.DateField(default=datetime.date(2019, 1, 13), null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='request',
            name='time',
            field=models.TimeField(default=datetime.time(6, 38, 54, 308119), null=True, verbose_name='Time'),
        ),
    ]
