# Generated by Django 2.0.10 on 2019-01-13 07:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0006_auto_20190113_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='time',
            field=models.TimeField(default=datetime.time(7, 4, 57, 711604), null=True, verbose_name='Time'),
        ),
    ]
